### ISSUE TITLE
Do not install all downstream at once

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue-integration-testing#1]
I don't think you should mix them all up like this, as downstream packages might have conflicting pins because they don't care about each other.

https://github.com/glue-viz/glue-integration-testing/blob/de90c4f0047579e20c873a05fb7aab3227653d09/tox.ini#L35-L37

Maybe addressing this would naturally fix the failures but I am not 100% sure.

**Comment by astrofrog** [comment]
This is deliberate though, to make sure they can indeed all be installed at the same time and work correctly

**Comment by pllim** [comment]
But why? Who would want to use WWT and Jdaviz at the same time?

**Comment by astrofrog** [comment]
I agree they might not be used at the same time but they might be installed in the same environment

**Comment by pllim** [comment]
Should they? If one of them becomes inactive, the burden then falls on the active package to maintain compatibility, which sometimes is impossible given how fast-paced some dependency upgrades happen.

**Comment by astrofrog** [comment]
I don't understand - all these packages are maintained by the glue project except for jdaviz and the point of this repo is precisely to do integration testing of the ecosystem. I can also just remove jdaviz from here if you prefer but I just added it for my convenience and I don't see the downside. I won't make jdaviz change things so that WWT continues to work! If anything this will help me make sure none of the glue packages break jdaviz?

**Comment by pllim** [comment]
> I won't make jdaviz change things so that WWT continues to work!

Okay, good to know. But something in this combo is failing the jobs though.

**Comment by pllim** [comment]
Anyway, we can talk about failures in #2 . Thanks!
